### ISSUE TITLE
svds in version 0.13-1 vs 0.12-0

### ISSUE THREAD

**Issue by benaernouts** [yixuan/RSpectra#11]
Dear Yixuan Qiu,

In the beginning of 2018, I installed the RSpectra 0.12-0 on my PC for using the SVDS function on mean-centered Mid Infrared spectra (X) to calculate the orthogonal signal (Wold et al., 1998).

e.g.: s <- RSpectra::svds(X,1,1,1)

In the meanwhile, I bought a new laptop and I was running the same code on the same dataset, giving totally different results. After a few hours of debugging, I found that the different results were caused by the version of the RSpectra package (RSpectra 0.13-1 was installed on the new laptop). After removing the RSpectra 0.13-1 and installing the RSpectra 0.12-0 on the laptop, I again obtained the same results as the ones I got before on the PC... But now I am wondering which version to use...
What has changed in de svds function in version 0.13-1 compared to 0.12-0? And which version is most suitable for my application?

BR,

Ben Aernouts
ben.aernouts@kuleuven.be

Reference: Wold, S., H. Antti, F. Lindgren, and J. Öhman. 1998. Orthogonal signal correction of near-infrared spectra. Chemom. Intell. Lab. Syst. 44:175–185. doi:10.1016/S0169-7439(98)00109-9.

**Comment by yixuan** [comment]
Could you provide a reproducible example to show the difference? Every new version has some subtle changes, and it is hard to tell which one is more accurate without any knowledge of your data.
