### ISSUE TITLE
Support dsCMatrix/dsRMatrix

### ISSUE THREAD

**Issue by flying-sheep** [yixuan/RSpectra#15]
The [`dsCMatrix`](https://stat.ethz.ch/R-manual/R-devel/library/Matrix/html/dsCMatrix-class.html) and [`dsRMatrix`](https://stat.ethz.ch/R-manual/R-devel/library/Matrix/html/dsRMatrix-class.html) classes are the only useful ones you don’t support yet. They’re like `dgCMatrix`/`dgRMatrix` except that only one triangle is stored and a `uplo` ∈ {`'U'`, `'L'`} slot exists to signify which.

The `dgRMatrix` docs say “These "..RMatrix" classes are currently still mostly unimplemented!”, but it still can’t hurt to implement a 2-line method for them.

PS: Thank you for the amazing package, I wish it had been there from the beginning!

**Comment by yixuan** [comment]
Yeah, adding new matrix classes should be a relatively easy task. However, the downside for these two is that they do not have a counterpart in the Eigen library. It may take some effort to implement all the [matrix operations](https://github.com/yixuan/RSpectra/tree/master/inst/include/RMatOp), but I'll gradually add them if I get some time. Also you are more than welcome to contribute. 😃

**Comment by flying-sheep** [comment]
Well, eigs_sym only uses a triangle, right? so you could just set `lower = A@uplo == 'L'` and use them as you’d use a dgCMatrix/dgRMatrix.

**Comment by yixuan** [comment]
The R code is good. What I mean is that the C++ part needs to correctly handle the `dsCMatrix` object, whose internal structure may be different from `dgCMatrix`.

**Comment by privefl** [comment]
You could always use the function interface, right?
```
library(Matrix)
mat <- sparseMatrix(i = 1:2, j = c(2, 2), x = 1:2, dims = c(3, 3))
(mat2 <- forceSymmetric(mat))
RSpectra::eigs_sym(mat2, 1)  # NOK
RSpectra::eigs_sym(function(x, args) as.vector(mat2 %*% x), 
                   k = 1, n = nrow(mat2))  # OK
```

Would this be slower to do it like this?

**Comment by flying-sheep** [comment]
@yixuan look at the comment in the R code: I *think* it’s the exact same thing except for the `uplo` property and the fact that only a triangle is specified. Which matches exactly your usage of `sym_dgCMatrix`. (I think you could just rename that to `dsCMatrix`)

**Comment by yixuan** [comment]
Great. I'll take a look later.

**Comment by yixuan** [comment]
I've checked the structure of `dsCMatrix` and can confirm that it is compatible with `dgCMatrix`. So, yes, go ahead and submit a PR. :smiley:

**Comment by flying-sheep** [comment]
I would do the following:

1. Check if you can somehow coerce a `dgCMatrix` to a `dsCMatrix` while setting the `uplo` slot and not copying the data
2. Check if that works if more than that triangle is filled in the `dgCmatrix`
3. Change the internal names `sym_dgCMatrix` → `dsCMatrix` and the `lower` parameter to use the `uplo` slot instead
4. change the R methods so that `eigs.dgCMatrix` delegates to `eigs_sym.dsCMatrix` if `isSymmetric(A)` and so on

**Comment by alexpghayes** [comment]
Thanks for starting the PR, this will be very useful for a project I'm currently working on!
