### ISSUE TITLE
Function interface for svds

### ISSUE THREAD

**Issue by andland** [yixuan/RSpectra#3]
Is it possible to implement the function interface for `svds`? Or is there a non-trivial way to use the `eigs` function interface to calculate the SVD with a function? I believe one would need to provide two functions: `A %*% x` and `t(A) %*% x`. At least that is what the [PROPACK library](http://sun.stanford.edu/~rmunk/PROPACK/lansvd.txt) has.

**Comment by yixuan** [comment]
Yeah, this is workable. I plan to implement this feature in the next version. Thanks.

**Comment by yixuan** [comment]
This feature has been added in the most recent version. See the bottom of the README page.

**Comment by yixuan** [comment]
The new version has been submitted to CRAN, so I think we can close this issue.

**Comment by andland** [comment]
Awesome, thanks!!
