### ISSUE TITLE
eigs and eigs_sym have trouble converging for which = "SA"

### ISSUE THREAD

**Issue by gdkrmr** [yixuan/RSpectra#4]
I stumbled across the following:
`eigs` and `eigs_sym` have trouble converging with the option `which = "SA"` and other values to get the smallest eigenvalues. After reading https://github.com/yixuan/RSpectra/issues/2 I made the observation that `eigs_sym` converges much faster and more reliably, if instead of which `sigma = -1e-5` is set.

**Comment by yixuan** [comment]
The general conclusion is that small eigenvalues are very difficult to converge, so whenever possible use the `sigma` parameter instead.

From your description it sounds like that your matrix is semi-positive definite, with one or more zero eigenvalues. When this is the case, it's suggested to first compute the rank of the matrix, so you know how many zero eigenvalues there are. Computing the rank is much more reliable and less expensive than computing the eigenvalues.

**Comment by gdkrmr** [comment]
Yes, you are right, the matrix is supposed to have one zero eigenvalue. I want the `n` smallest eigenvalues `> 0`, how would knowing the rank help me?

**Comment by yixuan** [comment]
I see. In this case I think your solution is the best since you already know the rank (`n - 1`).

**Comment by privefl** [comment]
I was curious, so I made a quick test:
```
N <- 50
M <- 100
X <- matrix(0, N, M)
X[] <- rnorm(length(X))
X2 <- scale(X)
S <- tcrossprod(X2)
# stopifnot(Matrix::rankMatrix(S) == (N - 1))

eigs <- eigen(S, symmetric = TRUE) # true values

printf <- function(...) cat(sprintf(...))
n <- 10
for (s in -10^(-5:0)) {
  eigs2 <- RSpectra::eigs_sym(S, k = n + 1, sigma = s)
  diff <- abs(eigs2$values[1:n] - tail(eigs$values[-N], n))
  printf("For sigma = %s,\n  - it took %d ops,\n", s, eigs2$nops)
  printf("  - max_diff is %e,\n  - mean_diff is %e.\n", max(diff), mean(diff))
}
```

It seems to do what we want. 
Moreover, in this case, it seems that if we take further `sigma` from 0 (for example, `-1` rather than `-1e-5`), we gain some accuracy. I think it is at the expense of rapidity of convergence (not in this case, but maybe for larger dimensions).

**Comment by yixuan** [comment]
If there is no further question on this issue, I may close it for now. Feel free to reopen it if additional discussions are needed.
